name: lucknowi_fashion_pos
description: "Professional Billing App for Lucknowi Fashion"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  excel_plus: ^2.17.0
  cupertino_icons: ^1.0.8

  # State Management
  provider: ^6.1.5

  # Local Database
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.6
  path: ^1.9.1

  # Date & Time
  intl: ^0.20.2

  # PDF
  pdf: ^3.11.3
  printing: ^5.14.2

  # Storage
  shared_preferences: ^2.5.3

  # File
  path_provider: ^2.1.5
  file_picker: ^10.3.2

  # Share
  share_plus: ^11.1.0

  # UUID
  uuid: ^4.5.1

  # Thermal Printer
  print_bluetooth_thermal: ^1.2.2

  # Barcode Scanner
  mobile_scanner: ^7.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true